
### Development environment configuration
[development.network]
rpc-url = "http://localhost:8000/rpc"
network-passphrase = "Standalone Network ; February 2017"
run-locally = false

[[development.accounts]]
name = "me"
default = true

[development.contracts]
# Remove client = true from development, we'll use staging instead
# quiz = { client = true }
# fungible_token_interface_example = { client = true }

### Staging environment configuration (TESTNET)
[staging.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[staging.accounts]]
name = "testnet-dev"
default = true

[staging.contracts]
# These will generate TypeScript clients for your deployed testnet contracts
quiz = { id = "CCJNWS5X3WHQNPXVVMRJV2SHCS43Y744E22V5QNI7K6OFXICKXPRNYYM", client = true }
fungible_token_interface_example = { id = "CDDS4YPZ5DWCVJKHVJTSZAB5YXDT44MNDZGZKDPMFZDEDCQ7SEOBJN47", client = true }

### Production environment configuration
[production.network]
rpc-url = "https://our-custom-rpc-provider.cool"
network-passphrase = "Public Global Stellar Network ; September 2015"

[[production.accounts]]
name = "official-team-account"
default = true

[production.contracts]
# soroban-atomic-swap-contract = { id = "C987..." }
# soroban-auth-contract = { id = "C876..." }
# soroban-errors-contract = { id = "C765..." }
# soroban-hello-world-contract = { id = "C654..." }
# soroban-increment-contract = { id = "C543..." }
# soroban-token-contract = { id = "C432..." }
# eurc = { id = "C321..." }
